_includes/header.html
demo/index.html
js/app/demo.js
js/app/eslint.js

I basically just copied what @TylerEich done and added a new page. If this will be merged, I'll create a pull request in eslint repository to update makefile script to copy compiled eslint file. For now, I just added it manually (v0.13.0).
This is very basic implementation of editor, but it's better the nothing. Also, demo.js should be probably updated to pull configuration from main eslint.json file (again, update makefile to copy it over).

Adding demo page to the site (Closes #3)

---

demo/index.html

Another attempt at fixing default height for the editor. I think this one should work.

Fixing height of the editor

---

js/app/demo.js
styles/demo.css

Fixing issue with jumping layout on hover, and content of popover.

Fixing demo issues

---

_includes/header.html
_includes/jumbotron.html
_includes/menu.html
_layouts/default.html
_layouts/demo.html
_layouts/doc.html
_layouts/post.html
index.html

Some additional SEO fixes
Since I removed all ".html" from links adding canonical link to all pages, because Jekyll's auto-generated sitemap includes them (can't verify locally that it works though).
Added microdata for SoftwareApplication (and included one line at the bottom of the page to provided supported Operating systems, which is required for SoftwareApplication).
Separated menu into it's own include
Added JSX support to the homepage.

Additional SEO enhancements

---

_includes/menu.html

Fixes #51 Not sure where it was linked from before...

Add Architecture to the menu

---

_includes/menu.html
_layouts/default.html
_layouts/demo.html
_layouts/doc.html
_layouts/post.html
index.html

This is the fix for #49 
I also added some HTML5 tags around the site for SEO. It also fixes #6

Fixing layout and adding HTML5 elements

---

docs/user-guide/integrations.md

Since I didn't see the integration.md in the official eslint repo I hope this PR is in the right place.
Having used 2 of these 3 plugins myself and planning to use the 3rd soon. So thought it would be useful for others.

Added more eslint integrations.

---

docs/developer-guide/contributing.md

Add missing URL to the Contributing page.

Add URL to eslint site issues

---

_includes/menu.html

Adding new link to developer guide menu.

Add shareable configs to the navigation

---

_posts/2015-05-09-eslint-0.21.0-released.md

Change github username to real name

---

js/app/demo.js

I think this would make the demo page much more useful.

Add saving of rules configuration on the demo page

---

js/app/demo.js

The "Ok" button had 164 identical click handlers attached to it, and they all were called on every click on the button.
Moved the click handler out of the for loop.

Fix demo page performance issue

---

docs/user-guide/integrations.md

The Code Climate CLI supports ESLint to locally analyze code

Add Code Climate to the integrations page

---

js/app/eslint.js

Revert browserified version of eslint that was accidentally checked in with newer dependencies.

Revert generated eslint file

---

_data/logos.yml

Correct link to Domain via logo

---

_includes/header.html
_includes/jumbotron.html
docs/getting-started/index.md
styles/overrides.css

Mostly copied from the GitHub README, with a few tweaks and additions.

New: Getting Started Page and Button (fixes #101)

---

js/app/demo.js

- Add rule name
- Add link to docs

Fix: Add rule to error list (fixes #85)

---

demo/index.html
js/app/demo.js
styles/demo.css

- Added `es6` env option
- Added `modules` ecmaFeature option

New: ES6 Support for demo (fixes #80)

---

js/app/demo.js

Hard-coding the list. Appears to work ok.

Fix: Missing Environments in Demo

---

docs/developer-guide/index.md
js/app/demo.js

Fixing issue with 1-based columns in demo and a broken link.

Fixing column numbers in demo (fixes #125)

---

js/app/demo.js

While there are a lot of lines changed. It's mostly just to make the code more readable. The change itself is basically just `$('#configuration').on('change', 'input[type=checkbox]', saveConfig);`

Fix: Update demo without OK button (fixes #138)

---

docs/user-guide/command-line-interface.md

Manual fix as suggested in https://github.com/eslint/eslint/pull/3787#issuecomment-140045791.

Docs: Fix closing code fence on cli docs

---

docs/developer-guide/shareable-configs.md

Noticed a missing single-quote while reading through the docs. Simple update to fix it.

Add missing single-quote

---

.gitignore

Fix: Adding .gitignore to avoid node_modules being committed (fixes #147)

---

_includes/footer.html
_includes/header.html
demo/index.html
js/app/demo.js

We had an extra jQuery in there which was causing conflicts this seems to work.

Demo: Demo and Search Working (fixes #156)

---

_posts/2015-12-11-eslint-v2.0.0-alpha-1-released.md

Docs: add new rules in `v2.0.0-alpha-1`

---

js/app/eslint.js
js/app/eslint.json

Let me know if more changes are needed but I think this should be fine. 
I have not tried it locally because I dont have the infrastructure in place to compile locally.

Fix: Revert the alpha changes from demo (fixes #167)

---

_posts/2015-12-23-eslint-v2.0.0-alpha-2-released.md

Links to issues in alpha-2 are wrong.

Docs: Fix wrong links

---

docs/developer-guide/nodejs-api.md

duplicate key

---

_layouts/doc.html
styles/overrides.css

Docs: Add icons for recommended and fixable rules

---

_layouts/doc.html

refs eslint/eslint#4355 
Added `title` attribute as requested by @gyandeeps here: https://github.com/eslint/eslint.github.io/pull/180

Docs: Add title attribute to icons (refs #4355)

---

docs/user-guide/integrations.md

Add Eclipse IDE which supports ESLint with [tern.java](https://github.com/angelozerr/tern.java/wiki/Tern-Linter-ESLint)

Add Eclipse IDE which supports ESLint with tern.java

---

docs/user-guide/integrations.md

fixes https://github.com/eslint/eslint/issues/5360

Add VSCode to list of supported Editors

---

_includes/menu.html

One more try. Didn't remove developer guide last time.

Fixing menu

---

docs/developer-guide/code-conventions.md

Pretty self-explanatory, I think.

Docs: Update copyright year in code-conventions.md

---

Gemfile
_config.yml
_includes/header.html
blog/index.html
styles/rouge.css

This should PR switches us from redcarpet to kramdown. I also added code highlighting while I was at it.

Upgrading Jekyll to 3.0.0 (fixes #194)

---

docs/user-guide/getting-started.md

Refs: https://github.com/eslint/eslint/issues/5530
Also, a few other minor updates.

Add command line link to getting started

---

.gitignore
Gemfile
README.md
_config.yml
feed.xml

I went through the official GitHub instructions for making GitHub pages work locally and made the appropriate changes. We can now use the official GitHub instructions to make this work with 100% compatibility.

Update: Make site work locally with GitHub pages

---

docs/user-guide/getting-started.md

refs eslint/eslint#5874
PR with same language for the eslint repo readme: https://github.com/eslint/eslint/pull/5919

Docs: Clarify init sets up local installation

---

_plugins/search.rb

Seems like you introduced a new pattern on the way page title are handled. Previously, I was parsing patterns like `rule description (rule name)` to correctly build the hierarchy. The regexp was failing on the new pattern of `rule name: rule description`.
I updated the code to take both patterns into account and fallback to the whole title in case a new pattern is added (instead of failing).
Should fix #258

Fix parsing of rule name for indexing

---

styles/overrides.css

Incremental style improvements:
* Update: increase padding-left from 2em to 3em at screen width > 1024px
* Fix: select text color for anchor links by class to avoid affecting color of headings that contain links
* Update: lighten the background color of code elements in headings
* Fix: specify max-width in px instead of em so it consistently limits length of headings including h1

Docs: style improvements

---

index.html

We aren't testing this anymore

remove io.js

---

demo/index.html
js/app/demo/app.jsx
js/app/demo/configuration.jsx
js/app/demo/editor.jsx
js/app/demo/environments.jsx
js/app/demo/events.js
js/app/demo/main.js
js/app/demo/message.jsx
js/app/demo/messages.jsx
js/app/demo/parserOptions.jsx
js/app/demo/requireConfig.js
js/app/demo/rulesConfig.jsx
js/app/schemas.json
js/vendor/JSXTransformer.js
js/vendor/jsx.js
js/vendor/text.js

I think I got this into a reasonable shape to merge it into the site. It can definitely be improved a lot more. But I figured it would be easier to get smaller PRs from others, then sitting on the incomplete demo.

Demo rewrite

---

_includes/header.html

Twitter example: https://dev.twitter.com/cards/types/summary

Update: Add support of twitter cards and others for other websites

---

docs/developer-guide/selectors.md

Also see: https://github.com/eslint/eslint/pull/8278

Docs: fix incorrect selector examples

---

js/app/parser/index.built.js
js/app/parser/parser.config.js

Update Espree Parser Configuration

---

parser/index.html
styles/parser.css

Use bootstrap for Espree Demo

---

js/app/demo/parserOptions.jsx

We forgot to add es2017 to the demo when we enabled it in ESLint.

Add es2017 to the demo

---

_posts/2017-04-21-eslint-v4.0.0-alpha.1-released.md

fix the link address of `array-callback-return`

fix a link address

---

docs/user-guide/integrations.md

See https://groups.google.com/d/msg/eslint/3RAn0QGcLcA/dQ2vhJ7xAAAJ

Docs: Link to eslint-plugin-local-rules for project-specific local rules

---

.gitignore
js/app/demo/FixedCode.jsx
js/app/demo/app.jsx

All the info in #322 
Only merge after `4.1.0` ([ESLint release issue](https://github.com/eslint/eslint/issues/8766)) is released as it uses functionality from it.

New: Add fixed code tab on the demo site (fixes #322)

---

js/app/demo/app.jsx
js/app/demo/requireConfig.js

This restores the save-state behavior of the old editor rather than reverting to the default state every time.

Save demo state in localStorage

---

js/app/demo/app.jsx

The list of problems and output can be considered a pure function of the text and options, so it's not necessary to store it separately as state and update it whenever the text or options change. Instead, just calculate it in the `render()` method.

Avoid unnecessary state in demo

---

js/app/demo/environments.jsx
js/app/demo/rulesConfig.jsx
js/app/demo/selectAllCheckbox.jsx

Add "select all" checkbox for rules/envs (fixes #123)

---

js/app/demo/app.jsx

See #390 for an explanation of the bug and why I think this is the correct fix.

Avoid deep-merging configs in demo (fixes #390)

---

js/app/demo/app.jsx
js/app/demo/editor.jsx

For the code sample [here](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHJlcXVpcmUtanNkb2M6IGVycm9yLCBuby11bmRlZjogZXJyb3IsIGtleXdvcmQtc3BhY2luZzogZXJyb3IgKi9cblxuZm9vYmFyXG5cbnZhciBmb28gPSAxO1xuZm9vKCk7XG5cbmZ1bmN0aW9uIGJhcigpIHtcbiAgICByZXR1cm47XG59XG5cbmJhcigpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19):
Before
After

Show end locations of problems in demo

---

js/app/demo/app.jsx
js/app/demo/configuration.jsx
styles/demo.css

Display version number in demo

---

_posts/2017-11-25-eslint-v4.12.0-released.md

Should be pretty self-explanatory.

Docs: Add v4.12.0 highlights

---

Gemfile

This might fix the page builds. I'm still not sure what's causing them.

Use github-pages gem

---

.travis.yml
Gemfile

Hopefully, this will fix build issues and reindex the site.

Upgrade algolia search plugin

---

js/app/parser/index.built.js
js/app/parser/index.js
js/app/parser/parser.config.js

There doesn't seem to have been a build since the last change to [`js/app/parser/index.js`](https://github.com/eslint/eslint.github.io/blob/master/js/app/parser/index.js), so this PR looks bigger than it actually is.
See the [second commit](https://github.com/eslint/eslint.github.io/commit/59974dbbd05621a4226f4accfd08f782fbbdf4d1) for the actual changes.

Update Espree demo config options

---

index.html

Helps to identify the name by just hovering over the logo.

Fix: Add title prop to sponsors html

---

parser/index.html

Fix loading espree due to https://github.com/eslint/eslint/pull/11467 .

Fix: correct loading espree

---

js/app/espree.js

See: https://github.com/eslint/eslint/pull/11478#pullrequestreview-210473157

Chore: add missing espree.js

---

_posts/2019-05-25-eslint-v6.0.0-alpha.2-released.md

Adding some more clarifying information to match the previous blog post

Update blogpost for v6.0.0-alpha.2

---

_posts/2019-06-09-eslint-v6.0.0-rc.0-released.md

I have noticed the URL was not a link.

Docs: make a URL a link.

---

.eslintrc.js
src/js/demo/app.jsx
src/js/demo/configuration.jsx
src/js/demo/editor.jsx
src/js/demo/environments.jsx
src/js/demo/events.js
src/js/demo/fixedCode.jsx
src/js/demo/message.jsx
src/js/demo/messages.jsx
src/js/demo/parserOptions.jsx
src/js/demo/rulesConfig.jsx
src/js/demo/unicode.js
src/js/main/image-lazy-loader.js
src/js/main/index.js
src/js/parser/index.js
src/js/parser/lib.js

This PR enables the ES6+ rules we had turned off. Most of the changes are from running the autofixer, but the second commit has some manual changes.

Chore: enable ES6+ rules and run autofixer

---

_includes/footer.html
package-lock.json
package.json
src/js/demo/app.jsx
src/js/demo/configuration.jsx
src/js/main/index.js

refs https://github.com/eslint/eslint.github.io/pull/600, https://github.com/eslint/eslint.github.io/pull/602
Trying this again. Sorry for missing this earlier!

Chore: bundle bootstrap.native using webpack

---

_posts/2019-08-18-eslint-v6.2.0-released.md

Docs: fix wrong link

---

src/js/demo/components/ParserOptions.jsx

Added a new option for the demo.

New: add parser option for ES2020

---

Gemfile

Let's see if this fixes the deploy issue...

Chore: faraday@0.15.3 (work around netlify issue)

---

src/js/demo/components/App.jsx
src/js/demo/components/Environments.jsx
src/js/demo/components/Message.jsx
src/js/demo/components/ParserOptions.jsx
src/js/demo/components/SelectAllCheckbox.jsx

Small refactor to use arrow functions where possible now that we're using Babel.

Chore: use arrow functions as callbacks in JSX

---

_posts/2019-11-07-funding-update.md

This is a blog post update about fundraising. I'd like to get this out tomorrow (07 November), so please take a look!

New: November fundraising blog post update

---

_tools/fetch-sponsors.js
package-lock.json
package.json

Restoring back changes to pull sponsor data from both OpenCollective and Github.

Update: Pull GitHub Sponsors donation data

---

_pages/index.liquid
src/styles/lib/sponsors.less

I took a stab at updating the styles. I'm sure there are other improvements we can make going forward! Please let me know what you think.

Update: update sponsor styles

---

package-lock.json

This is the result of running `npm audit fix`.

Upgrade: serialize-javascript vulnerability

---

package-lock.json
package.json

This is an attempt to see if this will fix our flaky Netlify builds.

Chore: regenerate lockfile and make output less verbose

---

_posts/2020-02-20-whats-coming-in-eslint-7.0.0.md

This is a blog post previewing the significant features and changes coming in v7.0.0. I did my best to explain the rationale behind some of the bigger changes, but do let me know if I didn't get it right.
Note that I only included what I thought to be significant changes, so please feel free to let me know if I missed anything. I didn't think changes to rules were important enough to merit inclusion (those will be better explained in the release notes).

New: Blog post announcing v7.0.0 features

---

_data/site.js
_includes/menu.liquid
_layouts/default.liquid
_layouts/demo.liquid
_layouts/doc.liquid
_layouts/post.liquid
_layouts/rule.liquid
_layouts/rules.liquid
src/styles/lib/banner.less
src/styles/lib/overrides.less
src/styles/main.less

This PR implements a reusable banner we can use when we want to announce something.
Screenshot:

Update: Add banner

---

_data/site.js
src/styles/lib/banner.less

Update: Add Black Lives Matter banner

---

README.md

I noticed missing periods, I also added a link to the MIT License

Docs: Added punctuation and link to license

---

public/_redirects

Following up on https://github.com/eslint/eslint/pull/13408, we'll need to merge this during our next release. Please do not merge before then, as the redirected link won't exist until then.

Update: redirect id-blacklist -> id-denylist

---

.github/workflows/ci.yml
.travis.yml

This PR switches our CI builds over from Travis to GitHub Actions. One fewer dependency!

Chore: switch to GitHub Actions

---

_posts/2020-08-19-eslint-google-season-of-docs-project-writer.md

This is the post to announce or GSoD participation and project selection

New: GSoD post

---

_posts/2020-09-16-supporting-eslint-dependencies.md

This is the promised post about how we are sponsoring our dependencies. It's set to publish on Wednesday.

New: Post about supporting our dependencies

---

docs/2.0.0/rules/object-curly-spacing.md

add missing closing parenthesis.

Docs: Fix typo of missing closing parenthesis

---

_tools/fetch-sponsors.js

Fix : Update the script to fetch GitHub sponsors (fixes #814)

---

_includes/footer.liquid
_posts/2017-04-07-eslint-v4.0.0-alpha.0-released.md
_posts/2018-03-30-eslint-v5.0.0-alpha.0-released.md
_posts/2018-04-13-eslint-v5.0.0-alpha.1-released.md
_posts/2018-05-28-eslint-v5.0.0-alpha.4-released.md
_posts/2018-06-09-eslint-v5.0.0-rc.0-released.md

Tiny update to fix the capitalization of GitHub.

Fix GitHub capitalization

---

_includes/ad.liquid
_includes/jumbotron.liquid
_layouts/post.liquid
src/styles/lib/ad.less

Switching the ad provider to Carbon Ads for better CPM. Still working through styling issues, but would like to get the preview site rendered to find issues.

Update: Switch to Carbon Ads

---

_posts/2021-06-08-whats-coming-in-eslint-8.0.0.md

This adds some further detail I forgot in the original post.

Update: What's coming in v8.0.0 blog post

---

_tools/fetch-sponsors.js

Resolve https://github.com/eslint/website/pull/874
Refers https://graphql-docs-v2.opencollective.com/contributionfrequency.doc.html

Fix: use correct order frequency in `fetch-sponsors` script

---

_data/team.json
_tools/fetch-team-data.js

This updates our team data fetch to include all of the fields needed for the new website design. This change has no effect on the current website.

chore: Update team data fetch

---

_posts/2014-01-19-breaking-change-formatter.md
_posts/2014-01-20-breaking-change-config-file.md
_posts/2014-06-21-formatter-breaking-change.md
_posts/2015-06-26-preparing-for-1.0.0.md
_posts/2016-03-30-updated-rule-policy.md
_posts/2016-04-14-welcoming-jscs-to-eslint.md
_posts/2016-09-15-changes-to-issues-and-pr-policies.md
_posts/2018-11-27-jsdoc-end-of-life.md
_posts/2020-02-20-whats-coming-in-eslint-7.0.0.md
_posts/2020-05-22-changes-to-rules-policies.md
_posts/2021-06-08-whats-coming-in-eslint-8.0.0.md

Added `teaser` property to some more posts.

chore: add teaser property to more posts

---

_data/sponsors.json
_pages/index.liquid
_tools/fetch-sponsors.js

This adds sponsorship totals to the sponsors data file. Right now we are calculating this on the homepage, but on the new website we need this data in a bunch of places, so it's easier just to have it right in the data file.

feat: Add totals to sponsors data file

---

_data/all_authors.json
_data/team.json
_tools/fetch-team-data.js

This adds titles to each profile in the `team.json` and `all_authors.json` files. These values aren't used in the current website but will be used in the new one.

chore: Add titles to team and author profiles

---

docs/rules/no-constant-binary-expression.md

Fixes missing heading in the newly added rule. I'll update the original file in eslint/eslint repo as well.

docs: fix heading in no-constant-binary-expression
