eslint/website

_posts/2015-02-21-eslint-0.15.0-released.md

This was showing the markdown for creating the link instead of creating the link.

Fix Markdown issue in 0.15 blog post

---

docs/developer-guide/working-with-rules.md
docs/user-guide/command-line-interface.md
docs/user-guide/configuring.md

This is a temporary fix for broken links until next release of ESLint. I completely forgot to update links inside dynamic documentation files and they are currently broken on the site. I will make sure to create a mirror pull request in the main ESLint repository. Sorry about that, completely slipped my mind. (I also couldn't verify that the links work locally... Local Jekyll doesn't support extension-less urls).

Temporary fix for broken links

---

docs/developer-guide/working-with-plugins.md
docs/rules/index.md

One more try, because gensite was using greedy regex to change links.

Fixing site documentation again

---

docs/user-guide/integrations.md

Previous repo was deprecated in favour of Gillespie59/eslint-plugin-angular (same author).

Link to maintained AngularJS plugin

---

js/app/demo.js

fixes #21 
This should add icons with errors/warning to the editor. It's too bad ESLint is only reporting starting position of error. Would be much nicer if it would report both start and end.

Adding Orion errors to the demo (fixes #21)

---

docs/developer-guide/source-code.md

The URLs at the top of http://eslint.org/docs/developer-guide/source-code aren't being turned into links.

make urls links

---

docs/user-guide/integrations.md

overcommit is a fully configurable and extendable Git hook manager that
includes out-of-the-box support for running ESLint.

Add link to overcommit Git hook manager

---

docs/developer-guide/governance.md

Updates governance policy to better match how we are actually operating.

Docs: Update governance policy

---

docs/user-guide/integrations.md

A tool to help established projects add ESLint without being overwhelmed by errors.

Add eslint-nibble to integrations page

---

js/app/demo.js

This solves the error we are seeing right now:
```sh
Uncaught TypeError: Cannot read property 'es6' of undefined
```

Fix: Demo fail on undefined property check

---

styles/overrides.css

This unfortunately can't go into bootstrap.less, because it is overridden in `main.936b04d2.css`.  The other option is to edit that file (main), which is possible, but ugly.

Fix: Scroll long code instead of wrapping (fixes #126)

---

docs/developer-guide/contributing/pull-requests.md

Fixes #146.
Changes in brief:
1. Link to code conventions in first half of Step 2.
1. Link to `issue-labels` section of "Working with Issues" page in second half of Step 2.
1. Tweaked commit message length info: New limit is 72 characters, enforced by `npm run check-commit` in ESLint repo.
NOTE: I wasn't sure how to build the website (i.e., parse the .md files), so I couldn't test my changes. If any of the link paths are wrong, please let me know and I will correct them. Sorry for the inconvenience.

Fix: Adding links to pull request guide for clarity. (fixes #146)

---

.gitignore
.travis.yml
_config.yml
_includes/footer.html
_includes/header.html
_includes/menu.html
_plugins/search.rb
js/app/search.js
styles/overrides.css
styles/search.css

As discussed in https://github.com/eslint/eslint.github.io/issues/69, here is my proposal for adding search to the eslint website using the Algolia API. You can test it live on http://eslint.algolia.com/.
It was done using our [Jekyll plugin](https://github.com/algolia/algoliasearch-jekyll). It includes a few specific tweaks to better adapt to the eslint doc (does not search in the blog changelogs, nor in previous rule versions for example). I've added several RWD displays of the searchbar + results.
It is currently hosted on one of my demo accounts, but if you open an account on Algolia, I'll make it unlimited and move all the data to it.
I've also added the necessary travis config files so it should rebuild the search index on every new push on master. It only requires you to configure …

Add Algolia search

---

Gemfile

Fixes #159 
The `bundle install` command ran by Travis should correctly find the `Gemfile` and install the needed plugins before running `bundle exec jekyll algolia push`.
Let me know if this works (or not).

Add Gemfile for Travis

---

docs/developer-guide/index.md

Hi guys,
This is a small mistake in the "Developer Guide" page:
http://eslint.org/docs/developer-guide/
Screenshot: https://twitter.com/ndaidong/status/680066898189369344
Cheers,
Dong

Fix duplicate section title

---

_plugins/search.rb

I've excluded all urls matching `/docs/2.0.0/` from the indexing, so those docs should not be displayed in the searchbar.
Should fix #177

Stop indexing v2.0.0 in search

---

_posts/2016-01-29-eslint-v2.0.0-beta.3-released.md

There was a backtick missing on the one-var-declaration-per-line line.
The other missing rules were the same ones that had to be fixed in the previous post by #184

Fixed typo, added rules mentioned in previous post

---

docs/user-guide/integrations.md

To reduce scrolling and visual complexity, make bulleted points (which have standard *-eslint packages) follow the pattern of Atom under Editors.
This is my warm-up exercise before the main work to improve information architecture.

simplify bulleted lists under Build Systems and Testing

---

docs/developer-guide/source-code.md

The Source code page has a link to github in it's opening sentence:
`ESLint is hosted at GitHub...`
but originally the link simply opened up github.com, which is not as useful or relevant than pointing to the actual __source code__ on github, since this is the "source code" page. So this PR aims to update that link to the actual source code. 
**Thanks for all the awesome work you do!!** I :heart: ESLint.

link to ESLint repo on source code page.

---

feed.xml

Docs: fix wrong URLs in feed.

---

docs/developer-guide/governance.md

Previously, the Contribution Guidelines link had a leftover `.html` extension, but that's now an index page.

Docs: Fix broken link in Governance

---

docs/user-guide/integrations.md

I noticed that the URL for Emacs/Flycheck was pointing to the old documentation for Flycheck. I also wanted to add a link to the `javascript-eslint` checker information.

Update integration information for Emacs/Flycheck

---

docs/developer-guide/contributing/changes.md

Feel free to close if you would prefer people go to the mailing list, but I think one or two other places put the mailing list and chat on the same level, as "media we would prefer that people use to ask questions".

Docs: Point to gitter chat as well as mailing list in change request docs

---

Gemfile
_plugins/search.rb

Fixes #216
Seems likes the move to kramdown caused the root issue. Kramdown seems
to have trouble converting markdown that looks like this:
```
```
Instead of creating the `h1`, it kept the `#`. Adding a newline
between the comment and the title fixes the issue, but I actually
fixed it in another way.
I realize that the current setting was indexing every rule, for every
version. I felt this was not the best way to do it, as this requires
blacklisting versions everytime you would add a new one. Instead,
I chose to only index the rules in `/docs/rules`, without any version
specified.
Turns out that the files in this directory do not have the HTML
comment bug..
I also updated the underlying gem and fixed a edge-case with the Rule
index page.
In the end it decreased the number of records from …

Update Algolia config

---

docs/maintainer-guide/governance.md
docs/maintainer-guide/issues.md
docs/maintainer-guide/pullrequests.md

Recently, the ESLint Reviewers concluded that it would be good to give ESLint Committers more authority in the project. This pull request proposes:
1. Committers should be allowed to merge some pull requests (bug fixes, docs, build-related, upgrades) on their own so long as they are non-breaking.
1. Committers should be allowed to label an issue as "accepted" if it is a bug fix, a new rule, or a non-breaking change to an existing rule. I think this change is good because it didn't make sense to allow Committers to accept new rules but not changes to existing rules.
Please let me know your thoughts. @eslint/eslint-team

Proposal: Increase scope of committership

---

docs/developer-guide/contributing/index.md
docs/developer-guide/contributing/new-rules.md
docs/developer-guide/contributing/rule-changes.md
docs/maintainer-guide/issues.md

This is a proposal for changing our procedure for accepting rules and rule changes. The general feeling amongst reviewers is that we have too many rules, and we're also spending a lot of time evaluating and adding new rules and rule changes.
This proposes that:
1. We only accept new rules if they are absolutely necessary for ESLint to be complete. Otherwise, we should suggest people create custom rules.
1. If a rule is so important that we accept it, then the rule must be implemented by the person who suggested it or a designee of that person. It will not be done by an ESLint team member.
1. Rule changes follow the same process: it must be important, and if we accept it, then the person who suggested it or a designee must implement it. It will not be done by an ESLint team member.
That …

Docs: Change to rule acceptance

---

js/app/parser/index.built.js
js/app/parser/index.js
js/app/parser/lib.js
js/app/parser/parser.config.js
parser/index.html

Fixes everything. Also displays the current Espree Version.  The only issue I have now is why does the `eslint` in this repo include the outdated `espree` version `2.2.5`? Other than that everything seems to work fine!

Update parser demo for espree 3.0 (fixes #196)

---

docs/developer-guide/code-path-analysis/index.md

http://eslint.org/docs/developer-guide/code-path-analysis/ is currently inaccessible. This seems to be because we have /docs/developer-guide/code-path-analysis.md and the assets directory docs/developer-guide/code-path-analysis/, and GitHub Pages is trying to serve the directory instead of the HTML file.
http://eslint.org/docs/developer-guide/code-path-analysis.html works because it is explicitly requesting the HTML file rather than the directory. Easy fix is to move /docs/developer-guide/code-path-analysis.md to /docs/developer-guide/code-path-analysis/index.md and change the links to the assets.
Alternatively, we could just rename the assets folder to something like code-path-analysis-assets, but I personally think the index.md solution makes more sense, given that the rest of the site …

Fix: /docs/developer-guide/code-path-analysis is pointing to the assets directory

---

styles/overrides.css

See https://github.com/eslint/eslint.github.io/issues/186#issuecomment-196460629

Docs: Style rules for columns of icons in tables of rules

---

Gemfile

It seems like after the last Gemfile change, the Algolia search went a bit crazy. Maybe reverting to this will fix it.

Revert Gemfile change

---

_layouts/doc.html

As discussed in https://github.com/eslint/eslint/pull/5807#issuecomment-207621143 and https://github.com/eslint/eslint/pull/5807#issuecomment-207689759, and then added to guidelines in https://github.com/eslint/eslint/issues/5446#issuecomment-191306528, the word additional makes it explicit that code is the same as or related to a preceding example.
This change will add the class which displays icon and background-color in recently edited rule docs:
* allowEmptyCatch option in no-empty
* allowArrowFunctions option in func-style
* exceptions option in id-length

Docs: Replacement rules for examples of additional code

---

_layouts/doc.html
styles/overrides.css

To implement the pictures in https://github.com/eslint/eslint/issues/5774#issuecomment-208400114 when screen width is less than 768px:
* Display glyphicons inline instead of hiding them. That implies change to display incorrect thumbs-down and correct thumbs-up at left of example sentences instead of code wells; see https://github.com/eslint/eslint/issues/5774#issuecomment-208401154
* Allow code elements to wrap, especially because some example sentences now have long options.

Docs: Style rules for glyphicons at narrow widths

---

_posts/2016-05-13-eslint-v2.10.0-released.md

The following options were added to `no-irregal-whitespace`.
- skipStrings
- skipRegExps
- skipTemplates

Adds `no-irregal-whitespace` as rule that options were added.

---

_config.yml
_layouts/rule.html
_layouts/rules.html
styles/overrides.css

This pull request adds the styles for a **table of contents**, which was recommended in https://github.com/eslint/eslint.github.io/issues/186#issuecomment-177734880.
Goals:
* for readability, limit length of lines to 80 characters for code and about 3 alphabets for text (from 1.5 to 2.5 is the guideline for prose reading, so close enough for tech content :)
* and make the lines fit on iPad (non-Pro) in portrait orientation
* be able to display a table of contents of headings level 2 through [EDIT2] 3, aligned at the top of the first ordinary content paragraph, if the width is at least iPad (non-Pro) in landscape orientation
* display inline code similar to GitHub so it looks noticeably different from hyperlinks
* [EDIT3] Instead of …

Docs: Prepare for table of contents

---

styles/overrides.css

@ilyavolodin Sorry, my bad. Several rules for `ul` and `.container` were not constrained to `main`.
`override: hidden` caused #262

Docs: constrain new style rules to main

---

docs/rules/index.md

Hopefully this will fix issue with extra `</col>` tags being displayed on the page. Can't test it locally, since it worked fine with the previous version

Fixing table rendering

---

docs/command-line-interface/index.html
docs/configuring/index.html

I'm pretty sure we don't link to these anywhere at this point (duplicates are in `user-guide`).

Chore: Remove old unused docs

---

_includes/footer.html

I thought it'd be nice to add a link to the gitter chat room to the footer since we're all pretty active there.

Docs: Add link to gitter chat room in the footer

---

_posts/2016-09-23-eslint-v3.6.0-released.md

It currently links to [`no-extra-paren`](http://eslint.org/docs/rules/no-extra-paren), which is a 404. It should link to [`no-extra-parens`](http://eslint.org/docs/rules/no-extra-parens) instead.

Docs: Fix a broken link in 3.6 blog post

---

_posts/2016-09-23-eslint-v3.6.0-released.md

The specification of ECMAScript® is ECMA-262. So I'm confused a bit in the ECMA2017 notation.
This PR changes ECMA2017 to ES2017.

Docs: ECMA2017 → ES2017

---

_posts/2016-09-30-eslint-v3.7.0-released.md

The link for `no-useless-computed-key` pointed to the rule page for `no-undef-init`.

Fix: fix incorrect link in 3.7.0 release.

---

docs/developer-guide/contributing/new-rules.md
docs/developer-guide/contributing/reporting-bugs.md
docs/developer-guide/contributing/rule-changes.md

Extension `.md` was missing in a few URLs.

Fix: Broken links to issue templates

---

README.md
package.json

I find myself constantly having to look-up the `jekyll` command to fire up the local server for the website. I thought having an npm script for it would be a good idea.

Chore: add `start` to npm scripts

---

cla/index.md

Made our old CLA page redirect to the JS foundation CLA page instead.
**Is there anything you'd like reviewers to focus on?**
I think not :)

Docs: redirect old CLA page to JS foundation CLA (fixes #254)

---

_includes/menu.html

Closes #303. For each dropdown in the menu, I added a link to its respective top-level section page. That way, if for any reason the scripts failed to load, the user will still be able to navigate to all the sub-sections.
**Is there anything you'd like reviewers to focus on?**
Nothing in particular.

Docs: add links to top-level sections in the menu (fixes #303)

---

docs/rules/index.md

**What is the purpose of this pull request?**
Visually improve the way deprecated rules that have no replacement would look like in the "Deprecated" section of the rules list. With this change, the current list would look like this:
Changed the rules list template to treat rules with an empty `replacedBy` property differently.
**Is there anything you'd like reviewers to focus on?**
We could also just leave the "replaced by" column empty instead, but I thought it looks like the table was a bit broken.. with this change, there is a small visual cue that the rule intentionally does not have any replacements.

Docs: better default for deprecated rules with no replacement

---

cla/index.md

Updated the redirect of the old CLA page to point to the new jsfoundation URL. Refs https://github.com/eslint/eslint/issues/7558
**Is there anything you'd like reviewers to focus on?**
Not really, I think.

Docs: fix CLA page redirect URL

---

_includes/menu.html

Adding "Formatters" to user guide menu and "Working with Custom Formatters" to developer guide menu
No changes have been made to the individual pages; those can be done separately.
NOTE: I haven't had a chance to install Jekyll on my (Windows) machine, so this is untested. But the HTML is pretty straightforward, so...

Adding formatter pages to menus

---

_includes/menu.html

We created a JSCS migration guide awhile ago, but I don't think we linked to it from anywhere, so JSCS users might not realize it exists.

Docs: include a link to the JSCS migration guide in the header dropdown

---

docs/rules/space-before-blocks.md

`space-after-keywords` appears as deleted in the docs and it's confusing to reference it.

Remove reference to deleted rule

---

_includes/menu.html

Given how important this page is for newcomers, we should ensure ease of access by including it in the User Guide dropdown. (Currently, it's linked to via a big button on the homepage, but the homepage doesn't have much other useful information and it's not hard to envision someone jumping straight to Configuring or the rules index.)

Docs: Add "Getting Started" link to User Guid menu

---

docs/developer-guide/nodejs-api.md
docs/rules/multiline-ternary.md
docs/rules/no-sync.md

This adds the documentation fixes from https://github.com/eslint/eslint/commit/1a89e1c53e543b483cb7a859a71f7917204cea18, https://github.com/eslint/eslint/commit/45f8cd9e06e9e5118b4980afcfcd4c6e0978b574, and https://github.com/eslint/eslint/commit/3c1dd6d8d3391b3568d6452e11d3d1336c629d5e. This should hopefully avoid confusion for users in the next couple weeks, in case we don't end up doing a patch release for 4.2.0.

Apply documentation fixes from ESLint repo

---

docs/user-guide/integrations.md

ALE is a newish lint engine for vim, works on vim 8 and neovim

Include ALE vim integration

---

_layouts/demo.html
js/app/demo/requireConfig.js

Now that the demo is served over `https`, it was failing to load resources over `http`, causing it to break.

Fix mixed content in demo

---

js/app/demo/message.jsx

Avoid unnecessary empty parens in demo messages for fatal errors

---

js/app/demo/rulesConfig.jsx

The RulesConfig component contains duplicated state for the active ESLint configuration, but the state should be only stored into the main app rather than being stored in RulesConfig. This updates RulesConfig to be a functional component instead.

Avoid duplicated state in rulesConfig

---

js/app/demo/app.jsx

Since the React state is stored in `localStorage`, this was inflating the required storage space even though nothing about the docs is stateful.

Avoid storing docs in React state in demo

---

js/app/demo/environments.jsx

This refactors the Environments component to do the following:
* Use a functional component rather than state (the state of the Environments component is already stored in the top-level app, so it should be passed down as a prop rather than being duplicated).
* Avoid local mutations when building columns
* Make the number of columns easy to change if necessary

Refactor Environments component in demo

---

js/app/demo/configuration.jsx

This updates the Configuration component to be a functional component (without state), since all the necessary state is stored in the top-level App component.

Refactor Configuration component to avoid duplicate state

---

js/app/demo/parserOptions.jsx

The ParserOptions component contains duplicated state for the active ESLint configuration, but the state should be only stored into the main app and passed down as props, rather than being stored in ParserOptions. This updates ParserOptions to be a functional component instead.

Avoid duplicate state in parserOptions

---

js/app/demo/app.jsx

This fixes an issue where the state from bootstrap is sometimes out of sync with the state stored in `localStorage`, resulting in the "messages" tab being active while displaying the fixed code instead.

Store demo tab state in react instead of bootstrap

---

js/app/demo/app.jsx

This fixes an issue where "#messages" would appear at the end of the URL when clicking the Messages tab in the demo. This was happening because we still use `<a>` tags for the tabs, and rely on Bootstrap to override the default click handler.
At some point it would be nice to use `<button>` instead of `<a>` for the tabs, but it seems to be nontrivial to do this while keeping Bootstrap's `nav` styling. This commit updates the navbar to add `data-toggle` to the Messages tab, to avoid changing the URL hash.

Don't change the URL hash when switching tabs in the demo

---

js/app/demo/app.jsx
js/app/demo/configuration.jsx
js/app/demo/environments.jsx
js/app/demo/parserOptions.jsx
js/app/demo/rulesConfig.jsx

Fixes https://github.com/eslint/eslint.github.io/issues/99
This updates the demo to allow code and config to be specified with a URL. Hopefully, this should make the demo an easy bug-reporting tool -- as an alternative to filling out information on Node versions etc., users could just paste a link to the demo with a particular code and config to demonstrate the bug.
The serialization format is:
`atob(JSON.stringify({ text: "the text", options: { /* the config */ })`
The serialized state is placed in the URL hash whenever the config or text is changed.
This commit also updates the config-building logic to make the serialized configs smaller, to prevent the URLs from getting too long. In particular, rules that were previously configured with `"off"` are now omitted from the config, and envs …

Allow a permalink to the demo with a given piece of code and config

---

js/app/demo/app.jsx
js/app/demo/rulesConfig.jsx

This makes the serialized configs smaller, which reduces the URL size.

Use 2 instead of "error" internally for demo configs

---

js/app/demo/app.jsx

Previously, the function to get state from `localStorage` would return an empty object as the default value if there was nothing stored. However, another part of the code was checking whether the value was falsy. This was causing crashes when going to https://eslint.org/demo without any stored state or additional data in the URL.
This commit updates the `localStorage` handler to return `null` as the default value.

Fix incorrect falsy check for localStorage stored state

---

js/app/demo/app.jsx

When loading code from a URL, the the value of `this.state.fix` would end up undefined. This would result in ESLint running in autofix mode, but the "fix" tab wouldn't get displayed, resulting in some missing problems.
[Example](https://eslint.org/demo/#eyJ0ZXh0IjoiZm9vIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InNlbWkiOjJ9LCJlbnYiOnt9fX0=)
Note that there are initially no errors, but switching to the "fix" tab and back causes a `semi` error to appear.

Fix issue where "fix" state was sometimes unset

---

js/app/demo/configuration.jsx

This adds a link to download the current config in the demo as a JSON file.
Unfortunately, it seems like browsers don't allow downloads to have a `.` as the first character of the filename by default (see [here](https://stackoverflow.com/questions/38931933/download-dotfile-using-html5-download-preserving-name)). So even though the `download` attribute specifies the filename as `.eslintrc.json`, the file actually gets saved as `eslintrc.json` (no dot). It's possible for the user to manually change the filename if they've configured their browser settings appropriately, but most users probably won't know to do that.

Add link to download .eslintrc.json file (fixes #110)

---

docs/rules/multiline-comment-style.md

This applies the changes from https://github.com/eslint/eslint/pull/9440 directly to the site, for the benefit of users who read the docs before the next release.

Improve multiline-comment-style docs

---

js/app/demo/app.jsx
js/app/demo/unicode.js

**What did you do?**
I wrote a code which includes non-ASCII characters, `✓` and `✘`, on [the ESLint demo](https://eslint.org/demo/#). <details>
```js
/*eslint lines-between-class-members: error */
//✘ BAD
class Bad {
foo() {
}
bar() {
}
}
//✓ GOOD
class Bad {
foo() {
}
bar() {
}
}
```
> https://qiita.com/mysticatea/items/ae0081b3da453b8a3304
</details><br>
**What did you expect to happen?**
I expected that I can get the URL for the code.
**What actually happened?**
I couldn't get the URL. The demo failed to generate the URL silently and reported an error in devtools.
This PR makes the ESLint demo supporting Unicode strings for URL hash. This is very useful in order to write release notes in Japanese or other languages, they can make links …

Fix: support Unicode in URL hash

---

js/app/demo/configuration.jsx
styles/demo.css

This updates the "Configuration" bar to store its opened state in React, to ensure it opens correctly (fixes #432).
As a bonus, the entire bar is now clickable, rather than just the text.

Handle demo config "opened" state in React (fixes #432)

---

_includes/footer.html

Currently, some resources are loaded from `https://eslint.org` even when running the site locally. Among other things, this was causing the demo to break because `requirejs` handled file extensions differently.

Ensure demo works when running site locally

---

_includes/menu.html

This makes the organization of the menu consistent so that all the migration guides are together below the divider.

Move integrations link above migration guides in the menu

---

docs/user-guide/getting-started.md

Incremental improvements to the Getting Started page. This page still might need to be redesigned a little bit, but at least some of the main issues have been addressed.
Question: Is there any point in mentioning the migration guides at all in a "Getting Started" page? If not, I'm happy to remove it outright.

Docs: Small updates to Getting Started page (refs #447)

---

_posts/2018-04-27-eslint-v5.0.0-alpha.2-released.md

This is basically the same as the highlights for last alpha release except that the version is changed. (Most of the actual discussion of highlights is in the migration guide.)

Add highlights for v5.0.0-alpha.2

---

docs/5.0.0/user-guide/migrating-to-5.0.0.md

This applies the commit from https://github.com/eslint/eslint/commit/a960d6958f09053ff0294447aab104d273c9dea9 onto master so that the changes will be visible on the site before the next release.

Update migration guide

---

js/app/demo/configuration.jsx
js/app/demo/rulesConfig.jsx

The bootstrap native popover objects were not being initialized. I added the initialization and refactored the show / hide toggle to match the bootstrap native [guide](https://thednp.github.io/bootstrap.native/)

Fix: show popover for rulesConfig (fixes #437)

---

js/app/image-lazy-loader.js

This fixes some linting errors in `image-lazy-loader`. These made it to master because we don't have a CI build that does linting yet on this repo (see https://github.com/eslint/eslint.github.io/issues/402).

Chore: fix linting errors in image-lazy-loader

---

js/app/demo/app.jsx

See https://github.com/eslint/eslint.github.io/issues/469 for details on the bug.

Fix: avoid changing URL fragment when switching demo tabs (fixes #469)

---

docs/rules/max-classes-per-file.md
docs/rules/prefer-object-spread.md

This will fix 404 responses for links that point to `max-classes-per-file` and `prefer-object-spread` rules.
Root cause is eslint/eslint-release#22. Hopefully we can fix that before next release!

Fix: Add missing rules

---

styles/less/overrides.less

This fixes the problem that icons at the beginning of paragraphs are hidden on smartphone device.
`@media (max-width: @screen-xs-max)` means small devices (`< 768px`) in Bootstrap 3.
Please see <https://getbootstrap.com/docs/3.3/css/#grid-media-queries>.

Fix: hidden icons on smartphone device

---

_includes/footer.html

This depends on algolia/docsearch-configs#440.
Refs #475. (If this and the docsearch-configs PR are merged, should fix that issue.)

Update: Request docs and blog content in Docsearch

---

_posts/2018-06-22-eslint-v5.0.0-released.md

This updates the formatting of the word "consistent" to be consistent with the formatting of the other option names in the blogpost.

Format "consistent" consistently

---

_posts/2018-07-12-postmortem-for-malicious-package-publishes.md

Fixes https://github.com/eslint/eslint-scope/issues/39

Postmortem for malicious package publishes

---

js/app/demo/parserOptions.jsx

This updates the parser options in the demo to use values like "2015" rather than "6" for the ecmaVersion option.

Update: Use official ecmaVersion names in demo

---

styles/less/overrides.less

In order to emphasize rule is **correct** or **incorrect**, I modify the `thumb-*` icon color

Add icon color for emphasize rule is correct or not

---

_data/team.json
_includes/menu.html
team/index.md

I've added a `/team` page an updated the "About" link in the heading to be a dropdown that has "About ESLint" and "About the Team". The grid is responsive, going down to just two columns on mobile and up to four columns on larger screens.

New: Add /team page

---

docs/rules/require-jsdoc.md
docs/rules/valid-jsdoc.md

This applies the changes from https://github.com/eslint/eslint/commit/617a2874ed085bca36ca289aac55e3b7f7ce937e to the live site.

Add deprecation notices to JSDoc rules

---

_tools/fetch-sponsors.js

I needed to clean up this script. I had added a hack for what I thought was a Open Collective bug, but it turns out I just misread the data. So, I'm removing that hack.

Fix: Incorrect sponsorship info

---

js/app/parser/index.built.js
js/app/parser/lib.js
package.json
parser/index.html

it uses the right path to bundled espree.
I had not noticed it was still using browserify, we can switch to webpack later(just like in the eslint repo).

Fix: parser demo not working (fixes #546)

---

_data/sponsors.json
_tools/fetch-sponsors.js
package-lock.json
package.json

Feedback from some sponsors is that they'd prefer sponsor logos be sorted by monthly donation amount (right now, it's basically sorted by when they made their first donation).
This PR updates the script to fetch sponsor data to include calculated monthly amounts and then sorts the data by that value.

Chore: Sort sponsor data by monthly donation

---

_data/team.json
_tools/fetch-team-data.js
team/index.md

This PR updates the team fetch script and team page to include members of the new "ESLint Reviewers" team. (Reviewers are only shown on the team page when there is at least one member.)

Update: Add Reviewers to team page (when present)

---

_data/sponsors.json
_tools/fetch-sponsors.js

- only process active subscriptions
- remove complicated monthlyDonation computation
- updated logo/avatar URLs
Fix:
- Airbnb being a 'backer' instead of 'gold-sponsor'
- GitKraken being featured with a cancelled/refunded subscription
Open Question: what to do with one time donations? Not sure how to compute their `monthlyDonation` For that reason, they're skipped mow.

Use Open Collective GraphQL API v2 as source

---

package-lock.json
package.json

There are currently 8 vulnerabilities found by `npm audit`, and the changes here are the results of running the following two commands:
```
npm install --save-dev less@3.9.0
npm update js-yaml --depth 2
```
I've run the `build`, `test`, and `less` npm scripts with no changes, so there shouldn't be any changes from these dependency upgrades.

Upgrade: fix vulnerabilities found by npm audit

---

_config.yml

The following warnings are printed out when we run `npm start`:
```
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.
```
Small change to update _config.yml to use `plugins` instead of `gems`. Please see https://github.com/jekyll/jekyll/pull/5130 for more details. Also changed `site.name` to `site.title` in `_config.yml`.

Chore: change gems to plugins in _config.yml (fixes #563)

---

docs/2.0.0/rules/valid-jsdoc.md

fixes https://github.com/eslint/eslint.github.io/issues/579
There's currently a Liquid syntax error in `docs/2.0.0/rules/valid-jsoc` that results in some text in the JSDoc block not rendering. This is caused by the use of double curly brackets in the comment (which Liquid is trying and failing to parse as a tag). I haven't found a way to escape them, but according to [this StackOverflow question](https://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll), it looks like the recommended way to solve this is just to treat it as raw text.
We weren't catching this in local dev because this directory is excluded from the generated site (I'm assuming to speed up incremental build time): …

Fix: syntax error in 2.0.0 valid-jsdoc (fixes #579)

---

js/app/demo/app.jsx

This commit just fixes the access point to get the demo working. Might not be the best long-term approach.
I'm also exploring (separate from this PR) whether it might be possible to add some unit tests to at least test that the React component can be generated.

Fix: Demo now uses updated Linter access point (fixes eslint/eslint#11873)

---

_config.yml
_includes/header.html
feed.xml

The site name is missing at `<title>` of the pages, and this PR fixes it.
Page template: https://github.com/eslint/eslint.github.io/blob/26276d3554706862f6a280f20063ab7e74108b81/_includes/header.html#L24

Fix: fix site name in title

---

README.md

This is provided by Netlify and shows the status of the last build in the README.

Chore: Add Netlify status badge to README

---

index.html

In exchange for the services they are providing to our project, Netlify asks that we link to their homepage from ours. Here is their full [Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/).
This PR adds a "Hosting" section to our list of sponsors with a link to https://www.netlify.com.
I would love to clean this section of the site up (and we will, when we get to the redesign!), but I think this makes the most sense for now. Please let me know if you disagree.

Enhancement: add Netlify badge to sponsors list

---

_config.yml
_plugins/config_url.rb

Currently, deployment preview builds are broken because we use `{{ site.url }}` in our Liquid templates to generate URLs. According to the [Netlify docs](https://www.netlify.com/docs/continuous-deployment/#environment-variables), it looks like the deployment preview URL should be set to this environment variable.
Please look over my Ruby - I'm not particularly familiar with the language :)

Fix: add Jekyll plugin to fix deployment preview URLs

---

src/styles/lib/sponsors.less

This adds some spacing below the sponsors rows.
Before:
After:

Update: add margin to sponsors rows

---

_includes/footer.html
package-lock.json
package.json
src/js/demo/configuration.jsx

This fixes a console error that can be seen when clicking on the "Fixed Code" tab in the demo:
It also theoretically allows us to take advantage of Webpack's tree shaking, since it looks like we're only using this one component.

Chore: import bootstrap.native components in bundles

---

.babelrc
src/js/demo/index.js
src/js/main/index.js
src/js/parser/index.js
webpack.config.js

I think this is what we want to do for now - Babel should rewrite 
```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```
to the individual polyfills the environments we have specified need. It would be nice to split out a common chunks bundle in the future.
I believe we're only using the bundles found [here](https://github.com/eslint/eslint/blob/master/webpack.config.js#L6-L7) for the site (please correct me if I'm wrong!), so we should be able to remove `core-js/stable` and `regenerator-runtime/runtime` from those bundles when the site is generated.

Chore: use preset-env useBuiltIns option

---

README.md
_config.yml
_pages/404.md
_pages/blog.html
_pages/cla.md
_pages/demo.html
_pages/index.html
_pages/parser.html
_pages/team.md
_pages/users.md
docs/developer-guide/architecture/index.md

This consolidates all the pages we have into a new `_pages` directory, cleaning up the root directory considerably :tada::
As I was working on this, I noticed that redirects are no longer working (which might be a result of moving off of GitHub Pages). For example, see https://eslint.org/docs/ or https://eslint.org/cla/. This PR doesn't fix this - I'll do that in a follow up PR. We should be able to use Netlify for redirects instead, as described [here](https://www.netlify.com/docs/redirects/).

Consolidate pages in _pages directory

---

_includes/footer.html
package-lock.json
package.json
src/js/demo/configuration.jsx

This reverts commit d062cf33164238edceb01c0938bb9a005425f447.
Sorry everyone - I missed a few other bootstrap components we're using. Will revert this so that the site works correctly while I fix up the rest of the site.

Revert "Chore: import bootstrap.native components in bundles (#600)"

---

_config.yml
_pages/cla.md
_pages/index.html
_redirects
docs/0.24.1/command-line-interface/index.html
docs/0.24.1/configuring/index.html
docs/0.24.1/user-guide/integrations.md
docs/0.24.1/user-guide/rules.md
docs/1.0.0/command-line-interface/index.html
docs/1.0.0/configuring/index.html
docs/1.0.0/user-guide/integrations.md
docs/1.0.0/user-guide/rules.md
docs/1.10.3/command-line-interface/index.html
docs/1.10.3/configuring/index.html
docs/1.10.3/user-guide/integrations.md
docs/1.10.3/user-guide/rules.md
docs/2.0.0/command-line-interface/index.html
docs/2.0.0/configuring/index.html
docs/2.0.0/user-guide/integrations.md
docs/2.0.0/user-guide/rules.md
docs/2.13.1/command-line-interface/index.html
docs/2.13.1/configuring/index.html
docs/2.13.1/user-guide/rules.md
docs/3.0.0/user-guide/rules.md
docs/user-guide/rules.md

Redirects are currently broken. This PR sets up redirect rules for Netlify (see docs [here](https://www.netlify.com/docs/redirects/)).
Would love if someone who has some more historical context around these redirects could look these over!

Fix: set up Netlify redirect rules

---

CNAME
_config.dev.yml
_config.yml

This PR does three things:
- I didn't realize files that start with `_` are not included in the build, so `_redirects` isn't currently being included
- We're serving a number of files that are copied (for examples, https://eslint.org/webpack.config.js). This should fix this. 
- Removes the `CNAME` file that is only necessary for GitHub Pages.

Fix: update files copied into _site

---

package-lock.json

Running `npm install` currently outputs the following: 
```
found 166 vulnerabilities (1 low, 165 high) in 7523 scanned packages
run `npm audit fix` to fix 165 of them.
1 vulnerability requires manual review. See the full report for details.
```
This PR updates the lockfile using `npm audit fix` using to fix 165 of these errors.

Upgrade: update lodash in package-lock.json

---

.eslintrc.js

This is out of date now that we're bundling all of the JS.

Chore: update .eslintrc.js

---

_posts/2016-04-14-welcoming-jscs-to-eslint.md

Old JSCS url (jscs.info) has now been taken over. Changing to github pages URL.

Update JSCS link

---

README.md

The repository name has been changed before, which caused invalid badge URL. This PR fixes it.

Chore: fix badge URL

---

Gemfile

refs https://github.com/eslint/website/issues/625
This reverts commit 8773fef25019eb3c43ade7ce5e08d57fee040aa8. Testing this out as suggested by https://github.com/eslint/website/issues/625#issuecomment-536374463.
Edit: Looks like it's fixed! 🎉

Revert "Chore: faraday@0.15.3 (work around netlify issue) (#624)"

---

src/js/demo/components/RulesConfig.jsx

This might solve #626, seems that the problem was with setting `checked` to `undefined`.
I'm not 100% sure that the problem is fixed, but it looks okay in my browser. Would be good if someone else could test this, too.

Fix: deselect all doesn't deselect all checkboxes in ESLint demo

---

src/js/demo/components/RulesConfig.jsx

When one checks the rule's box to enable/disable the rule and doesn't move the mouse right away, the popover doesn't hide, so the screen might end up looking like this:
It's probably because the original checkbox (label) is being removed from the DOM after the click and replaced with a new one, so `onMouseLeave` doesn't happen.
This PR should fix this by removing the code that manually shows and hides popovers. The Popovers are initialized for all elements in `Configuration.jsx` and it seems to work well by itself.

Fix: Popover doesn't hide after checking the rule

---

src/js/parser/parser.config.js

This PR adds `11` to the `ECMA Version` list in the parser demo.

Update: Add ECMA Version 11 in parser demo

---

src/js/demo/components/App.jsx
src/js/demo/components/BugReport.jsx
src/js/demo/components/Crash.jsx

This PR adds two things to the ESLint online demo:
* Demo will now handle and show linter's runtime errors instead of crashing.
* Demo will now report invalid autofix (parsing errors only).
Test code for crashing:
```js
/* eslint no-implicit-coercion:error */
let x ="" + 1n;
```
Test code for invalid autofix:
```js
/* eslint prefer-numeric-literals: ["error"] */
parseInt("11", 2)in foo
```

Update: handle crashes and report invalid autofix in ESLint demo

---

README.md
package.json

Adds a `start:docker` `npm` script for ease of development (no having to set up a Jekyll dev env :tada:!)  for those who have Docker installed. The current command removes the container after each run, but there are lots of things we can do to improve this in the future if we want.

Chore: start:docker npm script

---

src/js/demo/components/Configuration.jsx
src/js/demo/components/Environments.jsx
src/js/demo/components/ParserOptions.jsx
src/js/demo/components/Rule.jsx
src/js/demo/components/RulesConfig.jsx

This PR improves UI responsiveness by using `React.PureComponent` and `React.memo` in the configuration components.
Currently, the demo is re-rendering everything (editor, messages, envs, rules...)  on any change anywhere.
After this change, demo will re-render only what needs to be rendered again. That is:
* Editor, messages/fixed code - always.
* Parser options - only when there is a change in that section.
* Environments - only when there is a change in that section.
* Rules - only when there is a change in that section.
Additionally, when a rule is selected/deselected, only that checkbox will be rendered again. It's observable in React DevTools profiler. This is the only change that required some work - to convert `RulesConfig` to class in order to always pass the same callback …

Update: use PureComponent and React.memo in configuration components

---

src/js/demo/components/Environments.jsx
src/js/demo/components/ParserOptions.jsx

This warning is currently occurring because these two values can initially be `undefined`, making React treat it as an uncontrolled input. When the value is changed, it then switches to a boolean, causing it to be a controlled input and the warning to appear.

Fix: controlled to uncontrolled inputs warning (fixes #636)

---

src/js/demo/components/App.jsx

Fixes ESLint Demo as it's currently broken (when opened without configuration in URL or local storage).
Hot to reproduce: clear cache and open demo.

Fix: recommended rules crash

---

package-lock.json

This PR upgrades `eslint-utils@1.4.3` in our lock file to fix the security vulnerabilities reported by `npm audit` (see https://www.npmjs.com/advisories/1118).
This change is the result of running `npm update eslint-utils --depth 3` as recommended by `npm audit`.
```sh
$ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ eslint-utils                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint [dev] …
```

Upgrade: eslint-utils@1.4.3

---

_layouts/post.html
_pages/blog.html

This adds a sidebar with recent posts to each blog post on medium-sized screens and up. I wanted an easy way to look across a bunch of posts without needing to navigate back to the index. The sidebar disappears on smaller screens.

Update: Add sidebar to blog posts

---

_pages/index.html

This adds a count of our total contributors and monthly donations to the homepage. I think this is useful because Open Collective, for some reason, doesn't have this info easily available (I end up calculating it by hand every time).

Update: Add sponsor count and donation totals to homepage

---

_data/sponsors.json
_tools/fetch-sponsors.js
package-lock.json
package.json

This updates the `fetch-sponsors.js` script to include information from GitHub Sponsors. It normalizes the GitHub data to look the same as the Open Collective data (though without total donations, because that isn't available yet from GitHub).

Update: Pull GitHub Sponsors donation data (fixes #647)

---

_data/sponsors.json
_tools/fetch-sponsors.js
package-lock.json
package.json

Reverts eslint/website#651
This temporarily reverts changes to sponsors script, since Github permissions are not set correctly right now, and because of this, it blocks fetching sponsor date from OpenCollective.

Revert "Update: Pull GitHub Sponsors donation data (fixes #647)"

---

_posts/2019-02-12-funding-eslint-future.md

Was pointing to `/img/` instead of `/assets/img/`

Docs: Fix broken link to eslint collective logo

---

_pages/index.liquid
src/js/main/index.js

Small PR adding some Google Analytics events to the sponsor links on our home page. I'm not seeing the events fire locally (I'm actually not seeing any analytics requests going out), and I'm assuming that's due to it the requests not originating at `eslint.org`. Would love confirmation though!

Chore: add analytics to sponsor links on home page

---

_posts/2019-12-20-eslint-v6.8.0-released.md

The site is currently failing to build and I think it's most likely due to the unescaped Liquid interpolation syntax.

Fix: update 2019-12-20-eslint-v6.8.0-released.md to fix liquid parsing error

---

src/js/demo/components/App.jsx

I think there was a lack of environment preset(es2017, es2020) in the `Configuration List in demo page`. This PR is for adding es2017, es2020 on the list.
* before
* After

Update: add es2017, es2020 on env names

---

.eslintrc.js
src/js/demo/components/Message.jsx

I noticed that the links in the demo errors open in the same tab, navigating away from eslint.org. This PR adds a `target="_blank"` attribute to those links to open them in a new tab.

Update: open demo rule links in new tab

---

package.json

Our Netlify build is currently failing with the following output:
```sh
ERROR in ./src/js/demo/components/App.jsx
10:12:12 AM: Module not found: Error: Can't resolve '../node_modules/eslint/lib/linter/linter' in '/opt/build/repo/src/js/demo/components'
10:12:12 AM:  @ ./src/js/demo/components/App.jsx 43:0-68 63:17-29
10:12:12 AM:  @ ./src/js/demo/index.js
10:12:12 AM: ERROR in chunk demo [entry]
10:12:12 AM: demo.js
10:12:12 AM: /opt/build/repo/node_modules/babel-loader/lib/index.js??ref--4!/opt/build/repo/src/js/demo/index.js 8d9c08418e3c67681b9089441452bb1e
10:12:12 AM: Unexpected token (64:17)
10:12:12 AM: | }();
10:12:12 AM: |
10:12:12 AM: | var linter = new !(function webpackMissingModule() { var e = new Error("Cannot find module '../node_modules/eslint/lib/linter/linter'"); e.code = …
```

Chore: install demo deps during build

---

_data/rules.yml
package-lock.json

These descriptions are not run through the Markdown -> HTML generation step, since we blast these over as JSON and use the JSON file as the data source during site generation.
This PR fixes the current live site. Please also see the [corresponding PR](https://github.com/eslint/eslint/pull/12930) to fix this for future releases.

Docs: fix category descriptions for site generation

---

_posts/2015-06-26-eslint-0.24.0-released.md

I checked each link in the original issue https://github.com/eslint/website/issues/668.
Only two were in the blog.
- the link to `/docs/developer-guide/code-path-analysis.html` from `/blog/2016/02/eslint-v2.0.0-released` seems to not be broken.
- This PR fixes the link to `/blog/2015/preparing-for-1.0.0` from `/blog/2015/06/eslint-0.24.0-released`.
The rest were in docs, which cannot be modified in the website repo.  A new issue/PR should be created in the main eslint repo to fix the remaining broken links.

Fix: Broken link in 0.24.0 release notes (refs #668)

---

_includes/head.liquid

Currently, `og:image` is not displayed at Twitter card.
`og:image` is url, not path.
https://ogp.me/
https://deploy-preview-703--eslint.netlify.com/
https://cards-dev.twitter.com/validator

Fix: og:image

---

package-lock.json
package.json

This is the result of running `npm audit fix`. It doesn't fix all the `mkdirp`/`minimist` issues (it's a very widely used dep).

Upgrade: fix security vulnerabilities

---

docs/2.0.0/developer-guide/working-with-rules.md
docs/4.0.0/user-guide/formatters/html-formatter-example.html
docs/4.0.0/user-guide/formatters/index.md
docs/5.0.0/rules/index.md
docs/6.0.0/rules/default-param-last.md
docs/6.0.0/rules/function-call-argument-newline.md
docs/6.0.0/rules/grouped-accessor-pairs.md
docs/6.0.0/rules/index.liquid
docs/6.0.0/rules/no-constructor-return.md
docs/6.0.0/rules/no-dupe-else-if.md
docs/6.0.0/rules/no-import-assign.md
docs/6.0.0/rules/no-setter-return.md
docs/6.0.0/rules/prefer-exponentiation-operator.md
docs/6.0.0/rules/prefer-regex-literals.md
docs/7.0.0/user-guide/configuring.md
docs/maintainer-guide/governance.md

Since the docs for previous versions do not exist in the master branch of the eslint repo, it seemed that the links should be updated in the website repo.  I originally thought otherwise.  That is why this is a 2nd PR for the same issue.
This should resolve all broken links that were originally reported in #668.
Notable Notes:
The content of `/docs/user-guide/formatters/` from the v4.19.1 tag has been copied and pasted to `/docs/4.0.0/user-guide/formatters/`.
The content of `/docs/rules/index.md` from the v5.16.0 tag has been copied and pasted to `/docs/5.0.0/rules/index.md`.
The content of `/docs/rules/index.liquid` from the v6.8.0 tag has been copied and pasted to `/docs/6.0.0/rules/index.liquid`.  This caused new broken links to rules that don't seem to exist in `/docs/6.0.0/rules/`... …

Fix: Broken remaining broken links  (refs #668)

---

_includes/footer.liquid
_pages/404.liquid
_pages/blog.liquid
_pages/cla.md
_pages/demo.liquid
_pages/team.liquid
_pages/users.liquid

As reported [here](https://github.com/eslint/website/pull/716#issuecomment-618324833), there are a number of broken "Edit this page" links. This PR fixes them!

Fix: Edit this page links

---

_includes/footer.liquid

While working on https://github.com/eslint/website/pull/720, I noticed that we still have the JS Foundation listed in our footer. Note that the current link does redirect correctly.

Fix: update foundation name in footer

---

_data/rules.yml

Following up on https://github.com/eslint/eslint/pull/13242 and https://github.com/eslint/eslint/pull/13230, this removes the empty `Node.js and CommonJS` category on the [rules page](https://eslint.org/docs/rules/#node-js-and-commonjs).

Fix: remove empty Node.js and CommonJS category

---

public/_redirects

This PR fixes the redirects that were broken by [the bug fix](https://community.netlify.com/t/changed-behavior-in-redirects/10084) that Netlify implemented. I had been planning to do it before the deadline but then got sick - apologies that it's a bit late. I think marking all of these as forced redirects makes sense since we never want it to follow the shadowing behavior for the existing redirects.

Fix: use forced redirects in _redirects file

---

_includes/menu.liquid

Now that we have 7 migration guides in the menu, what do y'all think of putting them in descending order so the most recent version's guide will be listed first?

Docs: Add v7 migration guide to header menu

---

docs/rules/index.liquid

Fun with programming in Liquid! The [deprecated rules](https://eslint.org/docs/rules/#deprecated) currently link to broken links. To avoid having to keep track of 3rd party plugins, we can just not render namespaced rules.
For consistency, I will also follow up with a PR that removes these `replacedBy` fields in the deprecated Node.js/CommonJS rules to match what we did with the deprecated JSDoc rules.
**Edit**
Follow up PR: https://github.com/eslint/eslint/pull/13274

Fix: don't render links when plugin replaces core rule

---

docs/rules/index.liquid

The current version is rendering the raw backticks.

Docs: Change Markdown code fence to <code> tag

---

public/_redirects

This adds a redirect for /conduct that forwards to the OpenJS Foundation Code of Conduct. This is for convenience purposes in case the CoC changes location again.

Update: Code of conduct redirect

---

_data/site.js
_includes/footer.liquid
docs/maintainer-guide/governance.md
public/_redirects

This switches all chatroom links from Gitter to Discord. Also centralized our social links to make them a bit easier to change later on.

Update: Switch chat links to Discord (refs eslint/eslint#13029)

---

webpack.config.js

Demo is currently broken because of the esquery module change.
This should fix it, similar to eslint/eslint#13076
Just had to add `"browser"` as well, bundling was failing on `debug` module without that. I guess we should do the same in the eslint/eslint repo, too.

Build: add webpack mainFields

---

public/_redirects

This adds a redirect to the #tsc-meetings channel on our Discord server (suitable for sharing with others).

Update: Add redirect for TSC meetings channel

---

public/_redirects

This adds a redirect to the Discord #help channel. Hopefully if we include this in error messages we'll get fewer people showing up in #developers asking for help. (Also easier to share on Twitter)

Update: Add redirect for Discord help channel

---

.eleventy.js
_11ty/plugins/index.js
_11ty/plugins/markdown-plugins.js
package-lock.json
package.json

This adds the `markdown-it-anchor` plugin to the default Markdown generator in order to generate IDs for all headings in the site. This change will fix the issue we're having with Algolia search.

Fix: Ensure headings have IDs (fixes #747)

---

_data/team.json
_tools/fetch-team-data.js
package-lock.json
package.json

It turns out `@octokit/rest` changed its API completely without a major version bump, so things broke. I upgraded to the latest.

Fix: Team data fetch (fixes #757)

---

_posts/2020-08-06-salesforce-donates-10000-to-eslint.md

Fixes broken links in https://eslint.org/blog/2020/08/salesforce-donates-10000-to-eslint
I guess that an older version of `20202-08-06-salesforce-donates-10000-to-eslint.md` was used in #763, so I just copied the most recent version over `2020-08-06-salesforce-donates-10000-to-eslint.md`

Fix: Broken links in Salesforce donation blog post

---

_data/site.js
_includes/ad.liquid
_includes/head.liquid
_includes/jumbotron.liquid
_includes/text-ad.liquid
_layouts/doc.liquid
_layouts/post.liquid
_layouts/rule.liquid
_layouts/rules.liquid
_pages/demo.liquid
_pages/team.liquid
_pages/users.liquid
src/styles/lib/ad.less
src/styles/main.less

This ads Ethical Ads to each page (also removes the banner). The fallback if there is no ad, or if JS is disabled, is to show an ad for sponsoring ESLint.
I have an open question to them about how the ad looks on the homepage as it seems there's some weirdness with the CSS not being caused by us.

New: Add Ethical Ads

---

_posts/2020-08-28-eslint-public-roadmap.md

This is the long-promised blog post announcing our public roadmap. Once published, we should flip the public roadmap project to be public. This is set to be published on Friday, August 28, 2020.

New: Roadmap blog post

---

src/js/demo/components/App.jsx
src/js/demo/components/ParserOptions.jsx

This PR adds `2021` to the ECMAVersion list and `es2021` to the list of environments in ESLint's online demo.
Created as a draft since it needs ESLint `v7.8.0`.

Update: add ecmaVersion 2021 and es2021 environment to demo

---

_data/sponsors.json
_tools/fetch-sponsors.js

This PR fixes a bug with ESLint currently appearing as its own sponsor. This bug is caused by fetching all orders from OC, including those 3 that are actually from ESLint to its dependencies.
After this fix, the `fetch-sponsors.js` script will be fetching only incoming orders.
Since I can't fully test this because I can't run the script due to some GitHub issues, this PR needs help from someone who can.
Remaining steps:
1. Checkout this branch.
2. Set `ESLINT_GITHUB_TOKEN` env variable.
3. Run `node _tools/fetch-sponsors`.
4. Verify diff for `_data/sponsors.json`. The expected outcome is that 3 items with `"name": "ESLint"` should be deleted.
5. Commit and push to this branch if it's okay (I think we're usually fixing `_data/*` in the same PR, not waiting for the bot).

Fix: fetch only incoming orders from Open Collective in fetch-sponsors

---

_pages/index.liquid

This should help further qualify these links to search engines and perhaps further discourage SEO-focused "sponsorships". I found documentation that [Google](https://support.google.com/webmasters/answer/96569?hl=en) and [Bing](https://www.bing.com/webmaster/help/webmaster-guidelines-30fba23a) both support the value and treat it like `nofollow`, but I left `nofollow` as a fallback for any others that might not.

Update: Add rel=sponsored to sponsor links

---

_11ty/plugins/markdown-plugins.js

fixes #772
This PR changes the way we use `github-slugger` -> to NOT generate unique slugs.
It uses a documented API (see the end of [github-slugger#usage](https://github.com/Flet/github-slugger#usage) docs):
> If you need, you can also use the underlying implementation which does not keep track of the previously slugged strings (not recommended)
We didn't want to use this API because we wanted to avoid having duplicate IDs on the same page.
However, it turns out that `markdown-it-anchor` already avoids duplicate IDs on the same page [here](https://github.com/valeriangalliat/markdown-it-anchor/blob/de9e3a6cf18b24ab0b59bf787de78196b0135cef/index.js#L36), so it should be safe to not use the unique slug feature of `github-slugger`, which, since it can't be aware of the context, used to …

Fix: reset unique header IDs per page (fixes #772)

---

_11ty/plugins/markdown-plugins.js
package-lock.json
package.json

This PR changes header ID suffixes (which make IDs being unique on the page) to start from `-1` instead of `-2`.
This will align header IDs on `eslint.org`:
* https://deploy-preview-805--eslint.netlify.app/docs/developer-guide/scope-manager-interface#deprecated-members
* https://deploy-preview-805--eslint.netlify.app/docs/developer-guide/scope-manager-interface#deprecated-members-1
* https://deploy-preview-805--eslint.netlify.app/docs/developer-guide/scope-manager-interface#deprecated-members-2
with header IDs on GitHub:
* https://github.com/eslint/eslint/blob/master/docs/developer-guide/scope-manager-interface.md#deprecated-members
* https://github.com/eslint/eslint/blob/master/docs/developer-guide/scope-manager-interface.md#deprecated-members-1
* …

Fix: set unique slug start index to 1

---

_tools/fetch-sponsors.js

It turns out that because Substack is an organization instead of a user, we weren't pulling that data at all. This fixes our script to pull organization data, too.

Fix: Check for User and Organization sponsors (fixes #829)

---

.eslintignore
_11ty/plugins/markdown-plugins.js
_tools/dev-server.js
_tools/fetch-sponsors.js
_tools/fetch-team-data.js
package-lock.json
package.json
src/js/demo/components/App.jsx

it fixes the the error when installing with npm v7:
```bash
While resolving: eslint-website@1.0.0
npm ERR! Found: eslint-plugin-jsdoc@27.1.2
npm ERR! node_modules/eslint-plugin-jsdoc
npm ERR!   dev eslint-plugin-jsdoc@"^27.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-jsdoc@"^15.9.5" from eslint-config-eslint@6.0.0
npm ERR! node_modules/eslint-config-eslint
npm ERR!   dev eslint-config-eslint@"^6.0.0" from the root project
```

Chore: upgrade eslint-config-eslint

---

_posts/2021-06-08-whats-coming-in-eslint-8.0.0.md

Announcement of upcoming changes in v8.0.0. I purposely stuck with the most high-profile breaking changes, as we can dig into details of everything when we create our upgrade guide.

New: v8.0.0 blog post

---

_11ty/plugins/markdown-plugins.js

As discussed in https://github.com/eslint/eslint/pull/14743 with @mdjermanovic.
But that issue is sort of messy now, so I'll explain in details for why updating the `slugify` function here.
The current implementation would replace `--` in headers' ids with `-`, which means with header text like `--resolve-plugins-relative-to` we will have header id [`-resolve-plugins-relative-to`](https://eslint.org/docs/user-guide/command-line-interface#-resolve-plugins-relative-to) on website.
Generally it's not a big deal as long as we use the id of the single `-` version when linking to those headers. E.g.,
```md
[some text](#-resolve-plugins-relative-to)
```
But it will become a problem if we're going to browser the documentation on Github because Github would generate double `-` for the …

Fix: update slugify function

---

_layouts/doc.liquid
_layouts/rules.liquid
src/styles/lib/overrides.less

In the rule page, I wanted to search for all auto-fixable rules but the icon was an image instead of unicode, so I couldn't do a ctrl-f. So this PR changes chechmarks and wrenches to unicode to allow searching, which should make it easier for people to find the rules they're looking for.
Screenshot of how it looks below. Chechmarks could be ✅ or some other things instead if people prefer it.
before | after
--- | ---

Docs: Use emojis instead of images to indicate fixable/recommended rules

---

docs/rules/index.liquid

Would be https://eslint.org/docs/user-guide/command-line-interface#--fix instead of https://eslint.org/docs/user-guide/command-line-interface#fix

Docs: fix a broken link

---

_data/rules.yml
_layouts/doc.liquid
_layouts/rule.liquid
_layouts/rules.liquid
docs/rules/README.md
docs/rules/index.liquid
src/styles/lib/overrides.less

Fixes #859.
Other part required for this change: https://github.com/eslint/eslint/pull/14830

Docs: Display emoji/notice for rules with suggestions

---

docs/8.0.0/user-guide/migrating-to-8.0.0.md

s/Three new rules/Four new rules/

Chore: Fix typo in migrating-to-8.0.0.md

---

README.md

Switched the badge to show the GitHub actions CI status, as it does not look like Travis is actively used anymore.

Chore: Update CI build badge in README

---

.github/workflows/ci.yml

CI-related change.
updated `setup-node` action to `v2` for CI node workflow.
https://github.com/marketplace/actions/setup-node-js-environment

Chore: use `actions/setup-node@v2` in CI

---

_layouts/post.liquid

Inserts the blog post teaser directly into the body content of the post. In the new design, the teaser will be visually separated from the body content, but for right now, it's just the first paragraph. This is to help us prepare for the new site design.
Related to: https://github.com/eslint/eslint/pull/15285

docs: Update blog post layout

---

src/js/demo/components/Rule.jsx
src/js/demo/components/RulesConfig.jsx

Refers https://github.com/eslint/website/issues/878
Show `deprecated` tag if a rule is deprecated.

feat: explicitly specify if a rule is deprecated

---

_posts/2021-10-13-eslint-v8.0.1-released.md

Teaser of the blog-post announcing ESLint v8.0.1 accidentally says v8.4.1 instead of v8.0.1

docs: fix wrong version in v8.0.1 teaser

---

_posts/2014-11-15-es6-jsx-support.md
_posts/2014-12-24-espree-esprima.md
_posts/2016-04-19-eslint-joins-the-jquery-foundation.md
_posts/2016-07-01-eslint-new-rule-format.md
_posts/2016-07-15-jscs-end-of-life.md
_posts/2018-07-12-postmortem-for-malicious-package-publishes.md
_posts/2019-01-18-future-typescript-eslint.md
_posts/2019-02-12-funding-eslint-future.md
_posts/2019-05-01-funding-update.md
_posts/2019-09-09-indeed-donates-10000-to-eslint.md
_posts/2019-11-07-funding-update.md
_posts/2020-08-06-salesforce-donates-10000-to-eslint.md
_posts/2020-08-10-making-eslint-more-inclusive.md
_posts/2020-08-13-microsoft-donates-10000-to-eslint.md
_posts/2020-08-19-eslint-google-season-of-docs-project-writer.md
_posts/2020-08-28-eslint-public-roadmap.md
_posts/2020-09-16-supporting-eslint-dependencies.md
_posts/2020-10-07-year-paying-contributors-review.md
_posts/2020-12-10-automattic-platinum-sponsor-eslint.md
_posts/2021-01-13-chrome-gold-sponsor-eslint.md
_posts/2021-02-18-nx-gold-sponsor-eslint.md
_posts/2021-12-01-contra-gold-sponsor-eslint.md
package-lock.json

Hello!
I added the `teaser` property to remaining blog posts.
Fixes #903
Posts:
- `_posts/2021-12-01-contra-gold-sponsor-eslint.md`
- `_posts/2021-02-18-nx-gold-sponsor-eslint.md`
- `_posts/2021-01-13-chrome-gold-sponsor-eslint.md`
- `_posts/2020-12-10-automattic-platinum-sponsor-eslint.md`
- `_posts/2020-10-07-year-paying-contributors-review.md`
- `_posts/2020-09-16-supporting-eslint-dependencies.md`
- `_posts/2020-08-28-eslint-public-roadmap.md`
- `_posts/2020-08-19-eslint-google-season-of-docs-project-writer.md`
- `_posts/2020-08-10-making-eslint-more-inclusive.md`
- `_posts/2020-08-13-microsoft-donates-10000-to-eslint.md`
- `_posts/2020-08-06-salesforce-donates-10000-to-eslint.md`
- `_posts/2019-11-07-funding-update.md`
- `_posts/2019-09-09-indeed-donates-10000-to-eslint.md`
- …

chore: Add teaser property to remaining blog posts

---

_layouts/post.liquid

On blog posts with more than 1 author, the authors are now displayed, each with their correct GitHub URL.
When getting the `authors` array, I changed the `split` filter from `", "` to `","`.
Fixes #913

fix: Display authors with correct GitHub URL on blog posts

---

_posts/2022-03-25-eslint-v8.12.0-released.md
_tools/fetch-team-data.js

The fetch-team-data.js script is failing with the following error:
```
TypeError: frontmatter.authors is not iterable
```
(check on Jenkins)
I updated one blog post that didn't have `authors`, but that alone doesn't help because we're running the fetch script right after the release, and at that point there's a newly created release post without authors. Therefore, I also updated the script to check if `authors` exists.
I tested this locally and it works well, but I didn't commit the change in `team.json` so that the Jenkins job could update the team info both on the website and the README.md in eslint/eslint after the next release.

fix: check if blog post authors are specified in fetch-team-data script

---

docs/rules/no-constant-binary-expression.md

The example here wrongly used `x` instead of `a`.

Fixed typo in code comment

---

_layouts/doc.liquid
docs/rules/block-scoped-var.md
docs/rules/no-ternary.md

Updated the current website documentation page format to accept the new frontmatter introduced in https://github.com/eslint/eslint/pull/15869.

chore: Update rule docs format

---

_pages/users.liquid

Description:
Removed duplicate heading from eslint users (https://eslint.org/users) page.

docs: remove duplicate text

---

README.md
src/styles/lib/ad.less

The ads don't have proper height and width so it causes the content to shift from left to right and top to bottom in different pages. So we give explicit height for the ad banners to avoid those shifts
https://user-images.githubusercontent.com/32865581/169266152-65e498bb-6287-4161-aca7-f6f8708a8bb9.mov
https://user-images.githubusercontent.com/32865581/169265443-3f28d8f7-a73f-4ddf-ba2f-5bf055a9903f.mov
https://user-images.githubusercontent.com/32865581/169265457-0fb12361-c2c8-43e2-8c97-937168fe4220.mov

fix: removes layout shift caused due to ads

---

_11ty/plugins/markdown-plugins.js
docs/rules/semi.md
package-lock.json
package.json
src/styles/lib/overrides.less

In order to use containers in the new docs site, we also need to enable them here, otherwise we will get the plain text artifacts of the containers showing up in the web pages.
This pull request:
1. Enables `correct` and `incorrect` containers in markdown
2. Updates the `semi.md` file as an example
Related pull request for new docs site:
https://github.com/eslint/eslint/pull/15998

chore: Enable containers
